In [1]:
import numpy as np
from keras.preprocessing.text import Tokenizer, text_to_word_sequence
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import *

In [2]:
text='해보지 않으면 해낼 수 없다'

In [3]:
#텍스트 -> 토큰화
result=text_to_word_sequence(text)
print("원문:", text)
print("토큰화:", result)

원문: 해보지 않으면 해낼 수 없다
토큰화: ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
docs=['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
     '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
     '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.']

In [5]:
token=Tokenizer() #토큰화 함수
token.fit_on_texts(docs) 

In [6]:
print(token.word_counts)

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])


In [7]:
print(token.document_count) #문장 개수
print(token.word_docs) #각 단어가 포함된 문장의 개수
print(token.word_index) #각 단어의 인덱스

3
defaultdict(<class 'int'>, {'각': 1, '텍스트의': 2, '단어를': 1, '나누어': 1, '합니다': 1, '토큰화': 3, '먼저': 1, '해야': 1, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '결과는': 1, '있습니다': 1, '한': 1, '수': 1, '사용': 1, '할': 1})
{'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


In [8]:
docs=["너무 재밌네요","최고예요","참 잘 만든 영화예요",
     "추천하고 싶은 영화입니다", "한번 더 보고싶네요",
     "글쎄요","별로예요","생각보다 지루하네요",
     "연기가 어색해요","재미없어요"]
classes=np.array([1,1,1,1,1,0,0,0,0,0])#긍정:1,부정:0

In [9]:
#토큰화
token=Tokenizer()
token.fit_on_texts(docs)

In [10]:
#print(token.word_index)
x=token.texts_to_sequences(docs)
#x에 저장된 서로 다른 단어의 개수(길이)를 4로 통일(패딩)
paddedX=pad_sequences(x,4)
print("패딩결과:",paddedX)

패딩결과: [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [11]:
token.word_index

{'너무': 1,
 '재밌네요': 2,
 '최고예요': 3,
 '참': 4,
 '잘': 5,
 '만든': 6,
 '영화예요': 7,
 '추천하고': 8,
 '싶은': 9,
 '영화입니다': 10,
 '한번': 11,
 '더': 12,
 '보고싶네요': 13,
 '글쎄요': 14,
 '별로예요': 15,
 '생각보다': 16,
 '지루하네요': 17,
 '연기가': 18,
 '어색해요': 19,
 '재미없어요': 20}

In [12]:
#딥러닝 모델 작성
wordSize=len(token.word_index)+1 #0~20

In [13]:
#딥러닝
model=Sequential()
model.add(Embedding(wordSize, 8, input_length=4))
#Embedding(단어개수(voc),임베딩벡터크기(8차원),입력시퀀스길이)
#21차원 -> 임베딩(단어->밀집벡터) -> 8차원
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(paddedX,classes, epochs=20)

#model.summary()

#1만차원 -> 256, 512차원

# 예시) 단어종류:21가지->벡터공간->21차원===>임베딩===>2차원
#     100000...0000  => [1.5, 3.1]
#     00001...00000  => [1.0, 2.7]
# 임베딩 : 단어 -> 밀집벡터(dense vector)
#              신경망
# ex)원핫 인코딩 단어벡터의 차원이 50000차원 => 임베딩 => 2차원
# 하늘=[1000..000]#1이 1개, 0이 49999개 => 비효율적 => 임베딩(2차원)
# =>[1.5, 3.8]=하늘

Epoch 1/20
1/1 [==============================] - 0s 998us/step - loss: 0.6879 - accuracy: 0.7000
Epoch 2/20
1/1 [==============================] - 0s 989us/step - loss: 0.6857 - accuracy: 0.7000
Epoch 3/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6836 - accuracy: 0.7000
Epoch 4/20
1/1 [==============================] - 0s 0s/step - loss: 0.6815 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6793 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 998us/step - loss: 0.6772 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 997us/step - loss: 0.6750 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 0s/step - loss: 0.6729 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6708 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 997us/step - loss: 0.6686 - accuracy: 0.9000
Epoch 11/20
1/1 [==============

In [22]:
#LSTM을 이용한 뉴스(로이터) 분류기 

In [23]:
from keras.datasets import reuters
from keras.utils import np_utils

In [30]:
(xTrain, yTrain),(xTest,yTest)=reuters.load_data(num_words=1000, test_split=0.2)

In [31]:
category=np.max(yTrain)+1 #뉴스 카테고리(46가지), 0~45 => 1~46
print("카테고리:", category)
print("학습데이터:", len(xTrain)) #8982 건
print("테스트데이터:", len(xTest)) #2246 건
print(xTrain[1]) #길이 87인 뉴스 기사
print(yTrain[0]) #3 카테고리 뉴스

카테고리: 46
학습데이터: 8982
테스트데이터: 2246
[1, 2, 699, 2, 2, 56, 2, 2, 9, 56, 2, 2, 81, 5, 2, 57, 366, 737, 132, 20, 2, 7, 2, 49, 2, 2, 2, 2, 699, 2, 8, 7, 10, 241, 16, 855, 129, 231, 783, 5, 4, 587, 2, 2, 2, 775, 7, 48, 34, 191, 44, 35, 2, 505, 17, 12]
3


In [32]:
xTrain=pad_sequences(xTrain,maxlen=100)
xTest=pad_sequences(xTest,maxlen=100)
yTrain=np_utils.to_categorical(yTrain)
yTest=np_utils.to_categorical(yTest)

In [33]:
#모델 생성
model=Sequential()
model.add(Embedding(1000, 100))
model.add(LSTM(100, activation='tanh'))
model.add(Dense(46, activation='softmax'))

In [34]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [35]:
history=model.fit(xTrain, yTrain, batch_size=100, epochs=20,
         validation_data=(xTest, yTest))

Epoch 1/20
90/90 [==============================] - 8s 86ms/step - loss: 2.5756 - accuracy: 0.3471 - val_loss: 2.4142 - val_accuracy: 0.3620
Epoch 2/20
90/90 [==============================] - 7s 81ms/step - loss: 2.1359 - accuracy: 0.4498 - val_loss: 1.9228 - val_accuracy: 0.5085
Epoch 3/20
90/90 [==============================] - 9s 98ms/step - loss: 1.9116 - accuracy: 0.5030 - val_loss: 1.9162 - val_accuracy: 0.5031
Epoch 4/20
90/90 [==============================] - 9s 105ms/step - loss: 1.7524 - accuracy: 0.5536 - val_loss: 1.7868 - val_accuracy: 0.5383
Epoch 5/20
90/90 [==============================] - 10s 108ms/step - loss: 1.6777 - accuracy: 0.5700 - val_loss: 1.6863 - val_accuracy: 0.5699
Epoch 6/20
90/90 [==============================] - 10s 108ms/step - loss: 1.6492 - accuracy: 0.5736 - val_loss: 1.6540 - val_accuracy: 0.5757
Epoch 7/20
90/90 [==============================] - 9s 104ms/step - loss: 1.5964 - accuracy: 0.5851 - val_loss: 1.6014 - val_accuracy: 0.6002
Epoch 8

'hihello'->학습->모델->입력 h , 출력 i

In [37]:
sample ='hihello'
charSet =list(set(sample)) #코퍼스라고 하면 e,h,i,l,o가 vocabulary가 된다

In [38]:
charDic = {w: i for i, w in enumerate(charSet) }
charDic

{'i': 0, 'o': 1, 'e': 2, 'h': 3, 'l': 4}