In [1]:
import numpy as np

In [3]:
data=np.random.randint(30, size=(6,5)) #난수 생성

In [4]:
data

array([[12,  5, 19, 21, 18],
       [ 6,  6, 20, 13, 23],
       [22,  1, 26,  1, 28],
       [ 1, 26,  9,  7, 18],
       [27, 13, 14, 28,  5],
       [14, 27, 24, 28,  4]])

In [6]:
from numpy import *

In [7]:
mean(data) #전체 평균

15.533333333333333

In [10]:
mean(data, axis=0) #컬럼 단위 
mean(data, axis=1) #행단위 

array([15. , 13.6, 15.6, 12.2, 17.4, 19.4])

In [13]:
datas =(data-mean(data,axis=0))/std(data, axis=0)

In [15]:
mean(datas) #표준화된 전체에 대한 평균이므로 0이 나옴


1.4802973661668754e-17

In [16]:
mean(datas, axis=0)

array([ 9.13621031e-17,  0.00000000e+00, -1.85037171e-16,  1.48029737e-16,
        0.00000000e+00])

In [17]:
std(datas)

0.9999999999999999

In [18]:
std(datas, axis=0)

array([1., 1., 1., 1., 1.])

In [19]:
import scipy.stats as ss

In [20]:
ss.zscore(data) #한줄로 해결!

array([[-0.18844459, -0.78572473,  0.05783149,  0.45638696,  0.22694084],
       [-0.86684512, -0.68750913,  0.23132597, -0.32599068,  0.79429295],
       [ 0.94222295, -1.17858709,  1.27229285, -1.49955714,  1.36164505],
       [-1.43217889,  1.27680268, -1.6771133 , -0.91277391,  0.22694084],
       [ 1.50755672,  0.        , -0.8096409 ,  1.14096739, -1.24817463],
       [ 0.03768892,  1.37501827,  0.92530389,  1.14096739, -1.36164505]])

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
StandardScaler().fit_transform(data)

array([[-0.18844459, -0.78572473,  0.05783149,  0.45638696,  0.22694084],
       [-0.86684512, -0.68750913,  0.23132597, -0.32599068,  0.79429295],
       [ 0.94222295, -1.17858709,  1.27229285, -1.49955714,  1.36164505],
       [-1.43217889,  1.27680268, -1.6771133 , -0.91277391,  0.22694084],
       [ 1.50755672,  0.        , -0.8096409 ,  1.14096739, -1.24817463],
       [ 0.03768892,  1.37501827,  0.92530389,  1.14096739, -1.36164505]])

In [ ]:
mu

In [25]:
mu,sigma =10,2 #평균 10 표준편차 2 인 정규분포를 따르느 ㄴ난수 생성
x = mu+sigma* np.random.randn(100)

In [26]:
x

array([ 9.15283831,  5.08096677,  9.79066676,  8.34017576, 12.43586461,
        8.28938625, 13.43478425,  8.64413725, 11.98542953,  7.83925613,
        8.85710937,  7.68956093, 10.24604038,  4.80221179,  9.23599866,
        8.96902136,  9.06182356, 13.2140549 ,  7.45675448,  9.94872467,
        7.40666453,  9.50932294, 10.61687623,  8.16421391,  7.56555068,
        7.49027394, 10.74680448, 12.1903536 , 10.07876992,  9.69440308,
        8.98522971,  9.59469225, 13.33177989,  6.95183644,  9.62216748,
        8.28544878, 10.406873  , 10.58384725, 11.95184072, 10.73262199,
       10.05366158,  8.15284974,  5.8170522 ,  7.88474866, 11.24555666,
        8.91756032, 12.78911872,  8.72879536, 14.20168588, 12.14217582,
       10.46174041, 10.69232828,  6.81220714,  9.47110717,  8.93792109,
        8.23363856, 11.75475573, 10.83855387,  7.71407004, 11.0766391 ,
        9.62228293,  9.94870403,  7.22708434, 10.81022373, 13.29811324,
       10.68951558, 13.32447366,  8.07553404, 11.9598608 , 11.49

In [29]:
#연속형 변수를 이항변수화 (0아니면 1로 나누겠다)
from sklearn.preprocessing import Binarizer

In [30]:
x=np.array([[10,-10,1],
           [5,0,3],
           [0,7,5]])
x

array([[ 10, -10,   1],
       [  5,   0,   3],
       [  0,   7,   5]])

In [33]:
#0보다 크면 1로 0보다 작거나 같으면 0
bi =Binarizer().fit(x)
#threshold=0.0 기준값
bi.transform(x)

array([[1, 0, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [34]:
bi =Binarizer(threshold=4).fit(x)
bi.transform(x)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 1]])

In [97]:
#원핫인코더
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [36]:
data=np.array([[0,0,0,],
              [0,1,1],
              [0,2,2],
              [1,0,3],
              [1,1,4]])

In [39]:
# OneHotEncoder().fit(data)
ohe=OneHotEncoder()
ohe.fit(data)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [40]:
ohe.active_features_

AttributeError: 'OneHotEncoder' object has no attribute 'active_features_'

In [41]:
import pandas as pd

In [43]:
df= pd.DataFrame({
    'c1':np.random.randn(10),
    'c2':['a','a','a','a','a','b','b','b','b','b']
})
df

c1 c2
0 -0.820033  a
1  1.175780  a
2  0.546194  a
3 -0.318228  a
4 -0.419330  a
5  0.533160  b
6  0.054510  b
7 -0.209380  b
8 -0.902635  b
9  0.125715  b

In [44]:
bins =np.linspace(df.c1.min(),df.c1.max(),5)
bins
#c1 컬럼값을 기준으로 균등하게 5개로 영역을 나눔

array([-0.90263546, -0.38303167,  0.13657213,  0.65617592,  1.17577972])

In [47]:
df['c1bin']=np.digitize(df['c1'], bins)
df

pd.get_dummies(df['c1bin'], prefix='c1')

c1_1  c1_2  c1_3  c1_5
0     1     0     0     0
1     0     0     0     1
2     0     0     1     0
3     0     1     0     0
4     1     0     0     0
5     0     0     1     0
6     0     1     0     0
7     0     1     0     0
8     1     0     0     0
9     0     1     0     0

In [48]:
#원핫인코더 ㅣ 딸기 ->100, 사과0>010  바나나-> 001
#레이블 인코더 : 딸기 -> 1, 사과 ->2, 바나나->3
# le = LabelEncoder()
# df['collumn']= le.fit_transform(df['column'])

NameError: name 'LabelEncoder' is not defined

In [56]:
# train=pd.read_csv("titanic/train.csv")
test = pd.read_csv("titanic/test.csv")
train.shape #891, 12
test.shape #418,11

(418, 11)

In [59]:
train.dtypes
test.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [60]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [62]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [65]:
objDf=train.select_dtypes(include=['object']).copy()
objDf

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [66]:
objDf.isnull()

Name    Sex  Ticket  Cabin  Embarked
0    False  False   False   True     False
1    False  False   False  False     False
2    False  False   False   True     False
3    False  False   False  False     False
4    False  False   False   True     False
..     ...    ...     ...    ...       ...
886  False  False   False   True     False
887  False  False   False  False     False
888  False  False   False   True     False
889  False  False   False  False     False
890  False  False   False   True     False

[891 rows x 5 columns]

In [69]:
any([False, False, False]) #False
any([False, True , False]) #True
#any 함수 하나만 true여도 true
#all 함수 모두 true여야 true

True

In [72]:
objDf.isnull().any(axis=0)
objDf.isnull().any(axis=1)
objDf[objDf.isnull().any(axis=1)]  #단 한개라도 널이 있는 거 출력
objDf[objDf.isnull().any(axis=1)].shape

(689, 5)

In [74]:
objDf['Cabin'].value_counts()

C23 C25 C27    4
B96 B98        4
G6             4
C22 C26        3
E101           3
              ..
A31            1
D45            1
A36            1
C7             1
E49            1
Name: Cabin, Length: 147, dtype: int64

In [75]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [81]:
# train[train['Sex']=='male']['Sex'] =0
train.loc[train['Sex']=='male','Sex'] =0

In [82]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris       0  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry       0  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [85]:
train=pd.read_csv("titanic/train.csv")
test = pd.read_csv("titanic/test.csv")

In [86]:
train.loc[train['Sex']=='male','Sex'] =0
train.loc[train['Sex']=='female','Sex'] =1
test.loc[test['Sex']=='male','Sex'] =0
test.loc[test['Sex']=='female','Sex'] =1

In [87]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   1  38.0      1      0   
2                             Heikkinen, Miss. Laina   1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   1  35.0      1      0   
4                           Allen, Mr. William Henry   0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [88]:
test.head()

PassengerId  Pclass                                          Name Sex  \
0          892       3                              Kelly, Mr. James   0   
1          893       3              Wilkes, Mrs. James (Ellen Needs)   1   
2          894       2                     Myles, Mr. Thomas Francis   0   
3          895       3                              Wirz, Mr. Albert   0   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [114]:
train=pd.read_csv("titanic/train.csv")
test = pd.read_csv("titanic/test.csv")

In [93]:
train['Sex']=train['Sex'].apply(lambda x: 1 if x=='female' else  0 )
test['Sex']=test['Sex'].apply(lambda x: 1 if x=='female' else  0 )

In [94]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

다시 원 데이터 불러오기

In [98]:
def gen(data):
    #data의 성별을 숫자로 인코딩
    le=LabelEncoder()
    le.fit(['male','female'])
    data['Sex']= le.transform(data['Sex'])
    return data
train=gen(train)
# test=gen(test)

In [99]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [100]:
train['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [101]:
train['Embarked_C']= train['Embarked'].apply(lambda x : True if x=='C' else False)
train['Embarked_S']= train['Embarked'].apply(lambda x : True if x=='S' else False)
train['Embarked_Q']= train['Embarked'].apply(lambda x : True if x=='Q' else False)

In [102]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  Embarked_C  Embarked_S  \
0         A/5 21171   7.2500   NaN        S       False        True   
1          PC 17599  71.2833   C85        C        True       False   
2  STON/O2. 3101282   7.9250   NaN        S       False        True   
3            113803  53.1000  C123        S       False        True   
4            373450   8.0500   NaN        S       False        True   

   Embarked_Q  
0       False  
1       False  
2       False  
3       False  
4       False

#다시 원 데이터 불러오기

In [ ]:
#범주형 레코드를 원핫인코딩 
#sex-> sex_0 sex_1
# 0    1    0
#1     0    1
#Pclass -> Pclass1, Pclass2, Pclass3
#Embarked -> EnbarkedC, EmbarkedQ, EmbarkedS

In [115]:
def myData(data,col):
    for c in col:
        data =pd.concat([data, pd.get_dummies(data[c], prefix=c)], axis=1)
        data =data.drop(c, axis=1)
    return data

In [116]:
col=['Sex','Pclass','Embarked']
myData(train, col)

PassengerId  Survived                                               Name  \
0              1         0                            Braund, Mr. Owen Harris   
1              2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3         1                             Heikkinen, Miss. Laina   
3              4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5         0                           Allen, Mr. William Henry   
..           ...       ...                                                ...   
886          887         0                              Montvila, Rev. Juozas   
887          888         1                       Graham, Miss. Margaret Edith   
888          889         0           Johnston, Miss. Catherine Helen "Carrie"   
889          890         1                              Behr, Mr. Karl Howell   
890          891         0                                Dooley, Mr. Patrick   

      Age  SibSp  Parch            Ticket     Fare Cabin  Sex_female  \
0    22.0      1      0         A/5 21171   7.2500   NaN           0   
1    38.0      1      0          PC 17599  71.2833   C85           1   
2    26.0      0      0  STON/O2. 3101282   7.9250   NaN           1   
3    35.0      1      0            113803  53.1000  C123           1   
4    35.0      0      0            373450   8.0500   NaN           0   
..    ...    ...    ...               ...      ...   ...         ...   
886  27.0      0      0            211536  13.0000   NaN           0   
887  19.0      0      0            112053  30.0000   B42           1   
888   NaN      1      2        W./C. 6607  23.4500   NaN           1   
889  26.0      0      0            111369  30.0000  C148           0   
890  32.0      0      0            370376   7.7500   NaN           0   

     Sex_male  Pclass_1  Pclass_2  Pclass_3  Embarked_C  Embarked_Q  \
0           1         0         0         1           0           0   
1           0         1         0         0           1           0   
2           0         0         0         1           0           0   
3           0         1         0         0           0           0   
4           1         0         0         1           0           0   
..        ...       ...       ...       ...         ...         ...   
886         1         0         1         0           0           0   
887         0         1         0         0           0           0   
888         0         0         0         1           0           0   
889         1         1         0         0           1           0   
890         1         0         0         1           0           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 17 columns]

In [2]:
train=pd.read_csv("titanic/train.csv")
test = pd.read_csv("titanic/test.csv")

In [3]:
import missingno as msno

In [8]:
msno.matrix(train) #흰색 부분 결측치~

In [5]:
train['Age_mean']=train['Age']

In [10]:
train['Age_mean'].isnull().sum() #177
train['Age_mean'].fillna(train['Age'].mean(), inplace= True)
train.isnull().sum()


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Age_mean         0
dtype: int64

In [11]:
test['Age_mean']=test['Age']
test['Age_mean'].fillna(test['Age'].mean(), inplace= True)

In [13]:
train['Sex'].value_counts()
train['Gender']=(train['Sex']=='female')
test['Gender']=(test['Sex']=='female')

In [15]:
train['Gender']

0      False
1       True
2       True
3       True
4      False
       ...  
886    False
887     True
888     True
889    False
890    False
Name: Gender, Length: 891, dtype: bool

In [17]:
train['Embarked_S']=train['Embarked']=='S'
train['Embarked_C']=train['Embarked']=='C'
train['Embarked_Q']=train['Embarked']=='Q'

In [18]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_mean  Gender  \
0      0         A/5 21171   7.2500   NaN        S      22.0   False   
1      0          PC 17599  71.2833   C85        C      38.0    True   
2      0  STON/O2. 3101282   7.9250   NaN        S      26.0    True   
3      0            113803  53.1000  C123        S      35.0    True   
4      0            373450   8.0500   NaN        S      35.0   False   

   Embarked_S  Embarked_C  Embarked_Q  
0        True       False       False  
1       False        True       False  
2        True       False       False  
3        True       False       False  
4        True       False       False

In [19]:
test['Embarked_S']=test['Embarked']=='S'
test['Embarked_C']=test['Embarked']=='C'
test['Embarked_Q']=test['Embarked']=='Q'

In [20]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Age_mean  Gender  \
0  34.5      0      0   330911   7.8292   NaN        Q      34.5   False   
1  47.0      1      0   363272   7.0000   NaN        S      47.0    True   
2  62.0      0      0   240276   9.6875   NaN        Q      62.0   False   
3  27.0      0      0   315154   8.6625   NaN        S      27.0   False   
4  22.0      1      1  3101298  12.2875   NaN        S      22.0    True   

   Embarked_S  Embarked_C  Embarked_Q  
0       False       False        True  
1        True       False       False  
2       False       False        True  
3        True       False       False  
4        True       False       False

In [25]:
train['FamilySize'] =train['SibSp'] + train['Parch']+1 #가족의 수

In [26]:
train['FamilySize'].value_counts()

1     537
2     161
3     102
4      29
6      22
5      15
7      12
11      7
8       6
Name: FamilySize, dtype: int64

In [29]:
train['Family']=train['FamilySize']
train.loc[train['FamilySize']==1, 'Family']="S"
train.loc[(train['FamilySize']>1) & (train['FamilySize']<5), 'Family']="M"
train.loc[train['FamilySize']>=5, 'Family']="L"

In [30]:
train[['Family', 'FamilySize']].head()

Family  FamilySize
0      M           2
1      M           2
2      S           1
3      M           2
4      S           1

In [32]:
train['Family_S']=train['Family']=="S"
train['Family_M']=train['Family']=="M"
train['Family_L']=train['Family']=="L"

In [33]:
#test에도
test['FamilySize'] =test['SibSp'] + test['Parch']+1 

test['Family']=test['FamilySize']
test.loc[test['FamilySize']==1, 'Family']="S"
test.loc[(test['FamilySize']>1) & (test['FamilySize']<5), 'Family']="M"
test.loc[test['FamilySize']>=5, 'Family']="L"

test['Family_S']=test['Family']=="S"
test['Family_M']=test['Family']=="M"
test['Family_L']=test['Family']=="L"

In [34]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  ... Age_mean Gender  Embarked_S  \
0      0         A/5 21171   7.2500  ...     22.0  False        True   
1      0          PC 17599  71.2833  ...     38.0   True       False   
2      0  STON/O2. 3101282   7.9250  ...     26.0   True        True   
3      0            113803  53.1000  ...     35.0   True        True   
4      0            373450   8.0500  ...     35.0  False        True   

   Embarked_C  Embarked_Q  FamilySize  Family  Family_S Family_M  Family_L  
0       False       False           2       M     False     True     False  
1        True       False           2       M     False     True     False  
2       False       False           1       S      True    False     False  
3       False       False           2       M     False     True     False  
4       False       False           1       S      True    False     False  

[5 rows x 22 columns]

In [35]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin  ... Age_mean  Gender  \
0  34.5      0      0   330911   7.8292   NaN  ...     34.5   False   
1  47.0      1      0   363272   7.0000   NaN  ...     47.0    True   
2  62.0      0      0   240276   9.6875   NaN  ...     62.0   False   
3  27.0      0      0   315154   8.6625   NaN  ...     27.0   False   
4  22.0      1      1  3101298  12.2875   NaN  ...     22.0    True   

   Embarked_S  Embarked_C  Embarked_Q  FamilySize  Family Family_S  Family_M  \
0       False       False        True           1       S     True     False   
1        True       False       False           2       M    False      True   
2       False       False        True           1       S     True     False   
3        True       False       False           1       S     True     False   
4        True       False       False           3       M    False      True   

   Family_L  
0     False  
1     False  
2     False  
3     False  
4     False  

[5 rows x 21 columns]

In [38]:
train['Family'].value_counts()

S    537
M    292
L     62
Name: Family, dtype: int64

In [39]:
train['Fare'].describe()
#평균이 중앙 값에 비해 굉장히 크다

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [43]:
train['Pclass'].value_counts()
train['Pclass'] =train['Pclass'].astype('category')

In [44]:
train['Pclass'].dtypes

CategoricalDtype(categories=[1, 2, 3], ordered=False)