In [1]:
"""
딸기:OOV(Out of Voc)
코퍼스(분석 대상 분야 문서 집합)
문서1) 저는 사과 좋아요
문서2) 저는 바나나 좋아요
문서3) 저는 바나나 좋아요 저는 바나나 좋아요
"""
import numpy as np
from numpy.linalg import norm
from numpy import dot
#dot:두 벡터 내적
#norm:벡터의 크기

#     바나나 사과 저는 좋아요
#d1     0     1    1       1
#d2     1      0   1       1
#d3     2     0     2      2
doc1=np.array([0,1,1,1])
doc2=np.array([1,0,1,1])
doc3=np.array([2,0,2,2])

In [2]:
dot(doc1,doc2) #두 벡터의 내적
norm(doc1)

#코사인 유사도
#doc1,doc2
#doc1,doc3
#doc2,doc3


1.7320508075688772

In [3]:
#https://www.kaggle.com/rounakbanik/the-movies-dataset

In [4]:
import pandas as pd

In [5]:
data=pd.read_csv("data/movies_metadata.csv")
data.head()

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2  A family wedding reignites the ancient feud be...  ...   1995-12-22   
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4  Just when George Banks has recovered from his ...  ...   1995-02-10   

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  video vote_average vote_count  
0                    Toy Story  False          7.7     5415.0  
1                      Jumanji  False          6.9     2413.0  
2             Grumpier Old Men  False          6.5       92.0  
3            Waiting to Exhale  False          6.1       34.0  
4  Father of the Bride Part II  False          5.7      173.0  

[5 rows x 24 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45466 non-null  object 
 1   belongs_to_collection  4494 non-null   object 
 2   budget                 45466 non-null  object 
 3   genres                 45466 non-null  object 
 4   homepage               7782 non-null   object 
 5   id                     45466 non-null  object 
 6   imdb_id                45449 non-null  object 
 7   original_language      45455 non-null  object 
 8   original_title         45466 non-null  object 
 9   overview               44512 non-null  object 
 10  popularity             45461 non-null  object 
 11  poster_path            45080 non-null  object 
 12  production_companies   45463 non-null  object 
 13  production_countries   45463 non-null  object 
 14  release_date           45379 non-null  object 
 15  re

In [7]:
data=data.head(20000)

In [8]:
data['overview'].isnull().sum()

135

In [9]:
data['overview']=data['overview'].fillna('')

In [10]:
data['overview'].isnull().sum()

0

In [11]:
#TFIDF 구하기
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
Tfidf=TfidfVectorizer(stop_words='english')

In [13]:
TfidfMatrix=Tfidf.fit_transform(data['overview'])

In [14]:
TfidfMatrix.shape

(20000, 47487)

In [15]:
#코사인 유사도(linear_kernel)
from sklearn.metrics.pairwise import linear_kernel

In [16]:
cos_sim=linear_kernel(TfidfMatrix, TfidfMatrix)

In [17]:
cos_sim.shape
cos_sim

array([[1.        , 0.01575748, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01575748, 1.        , 0.04907345, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.04907345, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.08375766],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.08375766, 0.        ,
        1.        ]])

In [18]:
# 1. Toy Story 영화 제목 입력
# 2. Toy Story 코사인 유사도가 가장 높은 영화 제목을 추출

In [19]:
data.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [20]:
data['title'].duplicated().sum()

indices=pd.Series(data.index, 
                  index=data['title']).drop_duplicates()
print(indices.head())
#data.index

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64


In [21]:
# df=pd.DataFrame({'k1':['a','b','b','c','b','c']})
# df.duplicated(['k1']).sum()
# df.drop_duplicates()

In [22]:
data.index

RangeIndex(start=0, stop=20000, step=1)

In [23]:
pd.Series(data.index)

0            0
1            1
2            2
3            3
4            4
         ...  
19995    19995
19996    19996
19997    19997
19998    19998
19999    19999
Length: 20000, dtype: int64

In [24]:
indices['Batman']

Batman     585
Batman    8603
dtype: int64

In [25]:
def getRecommendation(title, cosine_sim=cos_sim):
    #title에 저장된 영화 제목으로 코사인 유사도가
    #가장 높은 10편의 영화를 추출
    idx=indices[title]
    simScores=list(enumerate(cosine_sim[idx]))
    #simScores의 유사도값을 기준으로 내림차순 정렬
    simScores=sorted(simScores, key=lambda x:x[1],reverse=True)
    simScores=simScores[1:21]
    movieidx=[i[0] for i in simScores]    
    return data['title'].iloc[movieidx]

In [26]:
getRecommendation("Toy Story")

15348                                    Toy Story 3
2997                                     Toy Story 2
10301                         The 40 Year Old Virgin
8327                                       The Champ
1071                           Rebel Without a Cause
11399                         For Your Consideration
1932                                       Condorman
3057                                 Man on the Moon
485                                           Malice
11606                                   Factory Girl
17189                                      Group Sex
7254                                  Africa Screams
5797                                   Class of 1984
13947                            The Gang's All Here
1032                                   The Sunchaser
3252                                 Bound for Glory
2157                               Indecent Proposal
7615     The First $20 Million Is Always the Hardest
6944                                Rivers and

In [27]:
#영화 리뷰 분류(이진 분류)

In [28]:
from keras.datasets import imdb

In [29]:
(traindata,trainlabels),(testdata,testlabels)=imdb.load_data(num_words=10000)
#자주 사용되는 단어 10000개만 추려서 사용

In [30]:
#traindata.shape #25000 개 훈련데이터(리뷰)
#traindata
trainlabels #0:부정, 1:긍정
testdata.shape

(25000,)

In [31]:
traindata[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [32]:
maxseq=[max(seq) for seq in traindata]
max(maxseq)
    

9999

In [33]:
word_index=imdb.get_word_index()#(단어, 인덱스)
reverse_word_index=dict([(value, key) #(인덱스, 단어)
      for (key, value) 
      in word_index.items()])

In [34]:
reverse_word_index
#traindata[0]
print(reverse_word_index.get(1000000,"?"))
#만약 인덱스가 100만이 존재하지 않다면 ?로 대체해라

#0, 1, 2 는 "패딩", "문서 시작", " 사전에 없음(oov)"
#을 인덱스로 약속되어 사용됨. 따라서 위 3개는 제외
#위 3개는 물음표 문자로 대체

decodedReview=" ".join(reverse_word_index.get(i-3,"?")
                       for i in traindata[0])

?


In [35]:
decodedReview

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [100]:
# tok.index_word
encoded=tok.texts_to_sequences(sentences)
encoded 
# 모든 문장들의 길이를 동일하게 해줘야 한다. 
# encoded에 저장된 문장들 중에서 가장 긴 문장의 길이를 구해보자 
[len(item) for item in encoded] #문장의 길이를 구해보자 
maxLen=max(len(item) for item in encoded) # 최대 문장의 길이 7
for item in encoded:
    while len(item)<maxLen:
        item.append(0)
padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [101]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [102]:
from tensorflow.keras.preprocessing import sequence

In [103]:
encoded=tok.texts_to_sequences(sentences)
padded=sequence.pad_sequences(encoded,padding='post')
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [104]:
"""
패딩: 문장의 길이가 다름 ->문장의 길이를 동일하게 해줌 
신경망 모델을 만들기 위해서는 먼저 패딩을 수행하여
모든 문장의 길이를 동일하게 해줘야 함. 
"""
sentences = [['barber', 'person'], 
            ['barber', 'good', 'person'], ['barber', 'huge', 'person'], 
            ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], 
            ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], 
            ['barber', 'went', 'huge', 'mountain']]
#정수 인코딩
from tensorflow.keras.preprocessing.text import Tokenizer
tok=Tokenizer()
tok.fit_on_texts(sentences)
#빈도수를 기준으로 단어 집합을 생성해주는 함수 
# tok.index_word
encoded=tok.texts_to_sequences(sentences)
encoded 
# 모든 문장들의 길이를 동일하게 해줘야 한다. 
# encoded에 저장된 문장들 중에서 가장 긴 문장의 길이를 구해보자 
[len(item) for item in encoded] #문장의 길이를 구해보자 
maxLen=max(len(item) for item in encoded) # 최대 문장의 길이 7
for item in encoded:
    while len(item)<maxLen:
        item.append(0)
padded_np = np.array(encoded)
padded_np
from tensorflow.keras.preprocessing.sequence import pad_sequences
sentences
#케라스에서 제로 패딩 
encoded=tok.texts_to_sequences(sentences)
padded=pad_sequences(encoded, padding='post') #반대로 나온것을 뒤집어서 출력 
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [112]:
def vectorize_sequences(sequences,dimension=10000):
    results = np.zeros((len(sequences),dimension))
    #25000행, 10000열 0으로 구성
    for i, seq in enumerate(sequences):
        print(i,'번 문서',seq)
        results[i,seq]=1
    return results
xtrain=vectorize_sequences(traindata)
xtest=vectorize_sequences(testdata)
xtrain[0]

882, 11, 6, 96, 14, 9, 24, 6, 1361, 237, 4, 1472, 248, 3230, 374, 9237, 5, 857, 32, 202, 14, 245, 21, 39, 14, 1573, 606, 863, 6, 1238, 1315, 3696, 297, 9600, 5, 4, 836, 266, 39, 406, 876, 5, 4, 1729, 7, 84, 247, 74, 6, 1019, 8194, 160, 232, 261, 14, 9, 35, 1427, 11, 4, 22, 198, 51, 166, 4, 2714, 6405, 38, 52, 10, 10, 46, 7, 470, 381]
24982 번 문서 [1, 13, 377, 149, 14, 22, 11, 5697, 54, 13, 16, 693, 12, 16, 427, 530, 13, 258, 4, 288, 43, 6, 378, 7, 1928, 596, 13, 16, 754, 3583, 56, 5, 180, 19, 9283, 13, 1247, 12, 5, 1177, 12, 8, 61, 362, 36, 447, 12, 99, 36, 1803, 51, 715, 4, 16, 1118, 13, 161, 376, 98, 151, 88, 13, 92, 104, 979, 4, 715, 2, 5, 2, 8, 1086, 291, 154, 362, 9, 55, 52, 2, 4, 690, 26, 530, 13, 131, 377, 98, 32, 637, 131, 377, 98, 54, 146, 3293, 50, 42, 751, 2, 4044, 9, 16, 141, 6, 530, 284, 45, 6, 2240, 29, 520, 12, 56, 10, 10, 48, 25, 169, 4, 22, 818, 12, 490, 119, 12]
24983 번 문서 [1, 13, 424, 825, 2, 9, 6, 753, 1179, 509, 422, 12, 28, 49, 52, 213, 21, 45, 6, 7319, 39, 160, 509

array([0., 1., 1., ..., 0., 0., 0.])

In [113]:
xtrain[0]

array([0., 1., 1., ..., 0., 0., 0.])